### ISSUE TITLE
exe/msi setup app

### ISSUE THREAD

**Issue by eliekh05** [HEIC-to-JPEG-Dev/FileSyncToy#14]
can i have exe/msi setup app

**Comment by MikeWilliams-UK** [comment]
Yes please

**Comment by eliekh05** [comment]
@HEIC-to-JPEG-Dev give us the exe or msi installer

**Comment by eliekh05** [comment]
@HEIC-to-JPEG-Dev where is the exe/msi i want it immediately

**Comment by eliekh05** [comment]
> All releases of the app will be through the Microsoft Store and will not be provided as a separate msix package.
> 
> 
> 
> Is there a specific reason you need a package outside of the App Store ?

i don't want to pay

**Comment by HEIC-to-JPEG-Dev** [comment]
This is a paid app only, may I suggest the original SyncToy from Microsoft which is free.

**Comment by eliekh05** [comment]
> This is a paid app only, may I suggest the original SyncToy from Microsoft which is free.

just do it this will save you alot of time instead of wasting time on money or remove the app from store and github

**Comment by HEIC-to-JPEG-Dev** [comment]
Why should it be free?

**Comment by eliekh05** [comment]
> Why should it be free?

if someone wants to get it without payments he can just download the app from github or the source and compile it if someone wants to use payment he can just search on microsoft store

**Comment by MikeWilliams-UK** [comment]
But the source code is not in this repo, so this option is a non starter.

**Comment by HEIC-to-JPEG-Dev** [comment]
Correct, this is not an open source project

**Comment by eliekh05** [comment]
> Correct, this is not an open source project

but i can find the appx file: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/4dfeea80-92ef-45fa-8f81-0d14e19a62f0?P1=1715714567&P2=404&P3=2&P4=M1H%2b2ZdKp4u4GWkvsMUzcw3Uctm5M2mZxn2FOA%2bxE4sJN1uNNpj0BoCcPehMZdDT4phwwSetEceKTtCOcZmCWg%3d%3d

Source: https://store.rg-adguard.net/

Select Product id then put 9nc0txt5zm7r in search box click on rm and select retail and press go download the second from top but you need to have on your microsoft account to use it

don't tell me you can't do it

**Comment by HEIC-to-JPEG-Dev** [comment]
So you have no problem then. Sorted.

**Comment by eliekh05** [comment]
> So you have no problem then. Sorted.

this is problem because i need to put the app needs to be on microsoft account which requires me to pay

**Comment by HEIC-to-JPEG-Dev** [comment]
While I don't understand your personal circumstances; there are free alternatives which can sync files for you. For this app, it is a paid app and will allways remain that way, although the price may vary with sales.
